### ISSUE TITLE
synchronize updated versions with rsbuild/core

### ISSUE THREAD

**Issue by iamxbs** [rspack-contrib/rsbuild-plugin-node-polyfill#2]
Expection：
When updating the @ rsbuild/core version, can we also update the @ rsbuild/plugin node polyfill. At present, the latest version of ployfill (v1.0.1) still relies on @ rsbuild/core 7.10, resulting in dependency conflicts after upgrading rsbuild/core versions.
Looking forward to your reply

**Comment by chenjiahan** [comment]
The `@rsbuild/core` is a devDependency, so it will not affect user's repo.

![image](https://github.com/user-attachments/assets/5b9d9d09-0de0-4414-8f9e-b9b19382fcca)

Anyway, I will update it to the latest version.
